# Generated by Django 4.0.3 on 2022-06-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='dpt_name',
        ),
    ]
