# Generated by Django 4.0.3 on 2022-06-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_dept_name_department_dpt_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=20)),
                ('stud_place', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('stud_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.department')),
            ],
        ),
    ]
