# Generated by Django 4.0.3 on 2022-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajaxdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField(max_length=12)),
            ],
        ),
    ]
