# Generated by Django 4.0.3 on 2022-06-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_ajaxdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajaxdata',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
