# Generated by Django 4.0.3 on 2022-06-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_ajaxdata_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=20)),
                ('st_contact', models.BigIntegerField()),
                ('st_email', models.CharField(max_length=50)),
            ],
        ),
    ]
