# Generated by Django 4.0.3 on 2022-06-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_remove_seller_s_pdct_id_product_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='s_email',
            field=models.CharField(max_length=40),
        ),
    ]
