# Generated by Django 4.0.3 on 2022-06-28 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_staff_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff_registration',
        ),
    ]
