# Generated by Django 4.0.3 on 2022-07-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('name', models.TextField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
